export * from "./enums.js";
export * from "./tables.js";
import {
  accounts,
  auditPolicyEvidence,
  aiKnowledgeEntries,
  canonicalEventLedger,
  contactIdentities,
  contactInboxProjection,
  contactMemberships,
  contactTimelineProjection,
  contacts,
  expeditionDimensions,
  gmailMessageDetails,
  integrationHealth,
  identityResolutionQueue,
  mailchimpCampaignActivityDetails,
  manualNoteDetails,
  pendingComposerOutbounds,
  projectAliases,
  projectKnowledgeBootstrapRuns,
  projectKnowledgeEntries,
  projectKnowledgeSourceLinks,
  projectDimensions,
  routingReviewQueue,
  salesforceCommunicationDetails,
  salesforceEventContext,
  sessions,
  simpleTextingMessageDetails,
  sourceEvidenceLog,
  syncState,
  users,
  verificationTokens
} from "./tables.js";

export const databaseSchema = {
  sourceEvidenceLog,
  aiKnowledgeEntries,
  contacts,
  contactIdentities,
  contactMemberships,
  projectDimensions,
  expeditionDimensions,
  gmailMessageDetails,
  integrationHealth,
  salesforceEventContext,
  salesforceCommunicationDetails,
  simpleTextingMessageDetails,
  mailchimpCampaignActivityDetails,
  manualNoteDetails,
  pendingComposerOutbounds,
  projectKnowledgeEntries,
  projectKnowledgeSourceLinks,
  projectKnowledgeBootstrapRuns,
  canonicalEventLedger,
  identityResolutionQueue,
  routingReviewQueue,
  contactInboxProjection,
  contactTimelineProjection,
  syncState,
  auditPolicyEvidence,
  users,
  accounts,
  sessions,
  verificationTokens,
  projectAliases
};

export type DatabaseSchema = typeof databaseSchema;
